const APPLY_ALERT = 'APPLY_ALERT';
const LOGIN_SUCCESS= "LOGIN_SUCCESS";
const SET_EMAIL= "SET_EMAIL";
const SET_PASSWORD= "SET_PASSWORD";
const SET_SIGNUP_DATA= "SET_SIGNUP_DATA";
const COUNT="COUNT"
export {  APPLY_ALERT, LOGIN_SUCCESS, SET_EMAIL, SET_PASSWORD, SET_SIGNUP_DATA, COUNT };